{
 "title": "Home",
 "tags": [
  "kubernetes",
  "pods",
  "production"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Pods Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=~\"Running|Succeeded\",namespace=~\"$namespace\"} > 0) by (pod))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=~\"Failed|Unknown\",namespace=~\"$namespace\"} > 0) by (pod))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{namespace=~\"$namespace\"} > 0) by (pod))\n- count(sum(kube_pod_status_phase{phase=~\"Failed|Unknown|Succeeded|Running\",namespace=~\"$namespace\"} > 0) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Count per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",node!=\"\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Pods Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"Succeeded|Running\"}) by (pod)\n/ sum(kube_pod_status_phase{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\",image!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\",image!=\"\"}[5m])) by (pod))\n/ (sum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\",image!=\"\"}[5m])) by (pod))\n/ (sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",namespace=~\"$namespace\"}) by (pod)\n/ sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",namespace=~\"$namespace\"}) by (pod)\n/ sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\", phase!=\"\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - kube_pod_status_initialized_time{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success)"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  }
 ]
}