{
 "title": "Pod Details",
 "tags": [
  "kubernetes",
  "pods",
  "staging"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum (kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU / L",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\", container!=\"POD\", image!=\"\"}[5m])) by (pod))\n/ (sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod\",namespace=~\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU / R",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\", container!=\"POD\", image!=\"\"}[5m])) by (pod))\n/ (sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM / L",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",namespace=~\"$namespace\",pod=~\"$pod\", container!=\"POD\", image!=\"\"}) by (pod)\n/ sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM / R",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",namespace=~\"$namespace\",pod=~\"$pod\", container!=\"POD\", image!=\"\"}) by (pod)\n/ sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\", container!=\"POD\", image!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container!=\"POD\", image!=\"\"}[1m]))",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pod\",namespace=~\"$namespace\",container!=\"POD\", container!=\"\",image!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pod\",namespace=~\"$namespace\",container!=\"POD\", container!=\"\",image!=\"\"}) by (pod)",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network RX/TX Total (bytes/sec)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) "
    }
   ]
  },
  {
   "title": "POD Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "TX : {{ pod_name }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod log",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.pod_name:\"$pod\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}